### ISSUE TITLE
Feedback and Success Stories

### ISSUE THREAD

**Issue by VatsalJagani** [VatsalJagani/splunk-app-action#19]
Feedback and Success Stories
- Please add comments to this issue if you wish to share the feedback.

**Comment by gjanders** [comment]
Thanks for creating this github action and mentioning it on community slack. I've used it for automating my appinspect check along with testing out updating the splunk python SDK updates.

For the appinspect check it seems to work perfectly. I had some failures and since I cannot see "what" failed in the output I run that manually outside the action. Is there a way to obtain the failure report from an appinspect run?

Finally, I also tested the python SDK update, while it partially worked I was not happy with the pull request:
https://github.com/gjanders/decrypt2/pull/26/files

It did appear to attempt to create the right files, however it added various .pyc files along with some extra pieces I do not require, all I require is the "splunklib" directory.

Furthermore it has assumed I'm using APP_ROOT/bin/splunklib, it would be nice if there was a variable for this as I sometimes use APP_ROOT/lib/splunklib, and sometimes another directory such as APP_ROOT/bin/lib/splunklib.

Thanks

**Comment by VatsalJagani** [comment]
@gjanders 

> Thanks for creating this github action and mentioning it on community slack. I've used it for automating my appinspect check along with testing out updating the splunk python SDK updates.

Appreciate that!!! Hope this will save your and your team's time in the future.



> For the appinspect check it seems to work perfectly. I had some failures and since I cannot see "what" failed in the output I ran that manually outside the action. Is there a way to obtain the failure report from an appinspect run?

Yes, you can find it under `Action` > Open last action run > `Artifacts` At the bottom of the page you should see it.
<img width="1281" alt="image" src="https://github.com/VatsalJagani/splunk-app-action/assets/20964366/fef7aba7-58ac-4759-9d59-c6c4c74b3df3">



> Finally, I also tested the python SDK update, while it partially worked I was not happy with the pull request: https://github.com/gjanders/decrypt2/pull/26/files
> It did appear to attempt to create the right files, however it added various .pyc files along with some extra pieces I do not require, all I require is the "splunklib" directory.

* Sorry to hear that, but I have fixed many problems now.
* Regarding `__pycache__` and `.pyc` files, that has been solved now. Use tag `VatsalJagani/splunk-app-action@v4.1`
* Regarding other packages like `deprecation` and `packaging`, that's the latest bug-fix from Splunk-Python-SDK. I would not recommend removing them as it would creat functionality problem. Alternatively you can move installation to different folder if you think those files are annoying.



> Furthermore it has assumed I'm using APP_ROOT/bin/splunklib, it would be nice if there was a variable for this as I sometimes use APP_ROOT/lib/splunklib, and sometimes another directory such as APP_ROOT/bin/lib/splunklib.

* Now you can use a new parameter called `splunk_python_sdk_install_path` with v4.1 to specify the path.
* Your workflow would look something like this:

```
- uses: VatsalJagani/splunk-app-action@v4.1
  with:
    app_dir: "."
    app_utilities: "splunk_python_sdk"
    my_github_token: ${{ secrets.MY_GITHUB_TOKEN }}
    splunk_python_sdk_install_path: "bin/lib"
```

* Also, you could use the custom command to avoid getting `.pyc` files into your final build as well if you see that as App-inspect failures.

```
- uses: VatsalJagani/splunk-app-action@v4.1
          env:
            SPLUNK_APP_ACTION_1: "find . -type f -name "*.pyc" -delete"
            SPLUNK_APP_ACTION_2: "find . -type d -name "__pycache__" -exec rm -r {} +"
          with:
            app_dir: "."
```

I hope this helps, Happy to help!!!
